### ISSUE TITLE
Rebase for LLVM 6 support

### ISSUE THREAD

**Issue by ThomasBrixLarsen** [Syniurge/Calypso#106]
LDC 1.9.0 adds support for LLVM 6. Some Linux distros have been shipping LLVM 6 for a while. I currently can't compile Calypso even with the prebuilt LDC LLVM 5.0.1.

**Comment by ThomasBrixLarsen** [comment]
I have been using the clang-9 branch. It's really awesome being able to use Qt from D. Closing.

**Comment by Syniurge** [comment]
Hush.. don't tell anyone yet! :)

And yes Calypso feels pretty solid for the first time. Thank you for using it, and don't hesitate to file issues if you encounter bugs to make it as robust as possible for the first release.

I'll be doing a few more rounds of important improvements before making a release/announcement.

**Comment by ThomasBrixLarsen** [comment]
Don't worry. I won't steal your thunder. :)

I'll add issues for what I've found so far. I have a PKGBUILD ready for ArchLinux. I'm also considering porting more of the Qt examples to D, though I think moc_.d needs more love for some of them.
