### ISSUE TITLE
Global operators not working

### ISSUE THREAD

**Issue by ThomasBrixLarsen** [Syniurge/Calypso#114]
globaloperator.h:
```c++
#include <string>

std::string &operator<<(std::string &s, const int &value)
{
        return s += std::to_string(value);
}
```

globaloperator.cpp:
```c++
#include "globaloperator.h"

int main()
{
        std::string str;
        str << 7;
        return 0;
}
```
globaloperator.d:
```d
pragma(cppmap, "globaloperator.h");
import(C++) *;

void main()
{
        std.string str;
        str << 7; //!!here!!
}
```

The C++ code compiles and works. But the D code outputs:
`globaloperator.d(7): Error: str is not of integral type, it is a basic_string!(char, char_traits!char, allocator!char)`

**Comment by Syniurge** [comment]
Global operators should work in most cases with b0b055c8b7aafb4b68a8d14b300d9821e7573cf4

However some cases mixing non-member and member overloaded operators, like `std::ostream <<` still need work.

**Comment by Syniurge** [comment]
So actually even `std::ostream <<` works nicely with basic disambiguation between non-member and member overload candidates, so I'll close this issue and if someone ever encounter a case where Calypso doesn't do enough disambiguation please open a new issue with the problematic code.
