### ISSUE TITLE
It looks like issue #16 is back

### ISSUE THREAD

**Issue by wilsonk** [Syniurge/Calypso#26]
Hello Elie,

I am getting the same issue as #16 again after yesterdays commits...or at least I think it is the same issue:

/usr/include/x86_64-linux-gnu/sys/stat.h(209): Error: function cpp.core.sys.posix.sys.stat.stat conflicts with static import cpp.core.sys.posix.sys.stat.stat at /usr/include/x86_64-linux-gnu/bits/stat.h(46)

I ran into this when testing the dlib demo I have again, but it also happened with a couple other test libs I have set up. I just thought I would let you know. The Qt demo also isn't compiling for me:

```
semantic3 QOpenGLDebugMessagePrivate
semantic3 QBitArray
#0 0x2494828 llvm::sys::PrintStackTrace(_IO_FILE*) (/home/wilsonk/Downloads/Calypso/build/bin/ldc2+0x2494828)
#1 0x2495dab SignalHandler(int) (/home/wilsonk/Downloads/Calypso/build/bin/ldc2+0x2495dab)
#2 0x7f5134072340 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x10340)
#3 0x916a04 cpp::FuncDeclaration::semantic(Scope*) (/home/wilsonk/Downloads/Calypso/build/bin/ldc2+0x916a04)
#4 0x7a04b1 TemplateInstance::tryExpandMembers(Scope*) (/home/wilsonk/Downloads/Calypso/build/bin/ldc2+0x7a04b1)
etc...
```

Maybe it works for you still? just wanted you make sure you knew about this stuff and that we have a record of it.

Thanks,
Kelly

**Comment by Syniurge** [comment]
> /usr/include/x86_64-linux-gnu/sys/stat.h(209): Error: function cpp.core.sys.posix.sys.stat.stat conflicts with static import cpp.core.sys.posix.sys.stat.stat at /usr/include/x86_64-linux-gnu/bits/stat.h(46)

Weird, will look into it tonight, I don't know which change triggered the error, but I still don't know why the error wasn't there in the first place either.

> The Qt demo also isn't compiling for me

It worked for me with Qt 5.5 before the push. However about 10 days ago during the first run when the PCH was generated compilation would fail, but then re-running the compilation would make it succeed. I haven't investigated this issue yet. It only happened with the Qt demo for some reason.

**Comment by Syniurge** [comment]
So the « stat » conflict seems to be gone for good with 015d23e8c545bb95e50a3c2d7ac16e5a42a7d5c9 and the Qt demo compiles on the first try for me.

Could you run gdb, wait for the crash, go into _#_3 cpp::FuncDeclaration::semantic and paste the result of:

```
print toPrettyChars(true)
print loc.toChars()
print type->toChars()
```

**Comment by wilsonk** [comment]
Ok. Here is what I got:

```
Program received signal SIGSEGV, Segmentation fault.
cpp::FuncDeclaration::semantic (this=0x439f1c80, sc=0x439f2240) at /home/wilsonk/Downloads/Calypso/dmd2/cpp/cppdeclaration.cpp:220
220         inst->syntaxCopy(this);
(gdb) print toPrettyChars(true)
$2 = 0x439f36b0 "cpp._.qSwap!(cpp.QByteArray.QByteArray).qSwap"
(gdb) print loc.toChars()
$3 = 0x439f3770 "/usr/include/qt5/QtCore/./qglobal.h(794)"
(gdb) print type->toChars()
$4 = 0x439f3900 "void(ref T value1, ref T value2)"
```

Hopefully that helps :)

**Comment by Syniurge** [comment]
Was this fixed? I can't even remember what was done or not done :)

**Comment by wilsonk** [comment]
This seems to have been fixed. I don't remember, off hand, what fixed it either but it seems ok now.
