### ISSUE TITLE
GDAL error again

### ISSUE THREAD

**Issue by wilsonk** [Syniurge/Calypso#37]
Hello Elie,

It looks like there was a regression for the GDAL example after the last few months since the last time I was around :)  

I get this error:

gdal.d(36): Error: cannot implicitly convert expression (& GDALTermProgress) of type extern (C) int function(double, const(char)_, void_) to extern (C++) int function(double, const(char)_, void_)
gdal.d(46): Error: cannot implicitly convert expression (& GDALGenImgProjTransform) of type extern (C) int function(void\* pTransformArg, int bDstToSrc, int nPointCount, double\* x, double\* y, double\* z, int\* panSuccess) to extern (C++) int function(void_, int, int, double_, double_, double_, int*)

Thanks,
Kelly

**Comment by Syniurge** [comment]
Fixed with cce70f21f978c56cb808e51af5647dfcfc16e995.
