### ISSUE TITLE
Build with external clang

### ISSUE THREAD

**Issue by Nekroze** [Syniurge/Calypso#40]
I am trying to build your awesome project with a pre-installed version of clang, still 3.6 but pre-built and on the lib and include paths but I am not having any success and I am rather new to cmake.

Is there a way to get cmake to do this or is there some switch that your project can read to use a different clang without having to build it?

Unless your project modifies clang but it doesn't seem to so this should be doable and I think a good feature to have, it would keep compile times down as well.

**Comment by Syniurge** [comment]
Hi,

Actually the Clang fork has some minor modifications for Calypso, but only the 3.6 branch: https://github.com/Syniurge/clang/commits/release_36

Initially Clang was external and I tried to stick to vanilla with various hacks, but came to a point where this wasn't possible anymore and an internal fork was unavoidable.

**Comment by Nekroze** [comment]
@Syniurge Fair enough, makes sense.
