### ISSUE TITLE
VTK symbol conflict error (nested enum having the same name as a field)

### ISSUE THREAD

**Issue by wilsonk** [Syniurge/Calypso#42]
Hello Elie,

There seems to be one major error holding back a few nice VTK examples. I have isolated it so that I could add it to the basics.hpp example test code like so:

```
    template <class T>
    class testClassTemplate:
    public testClassTemplate<arrayOfTen<T>>
    {
    public:
      enum test {
        FREE,
        DELETE
      };

    protected:
      int test;

    };
```

Then instantiate from basics.d ala. "auto tt = new testClassTemplate!(arrayOfTen!int);" and you get this error:

```
basics.hpp(129): Error: variable cpp.test.testClassTemplate.testClassTemplate!(arrayOfTen!int).testClassTemplate.test conflicts with enum cpp.test.testClassTemplate.testClassTemplate!(arrayOfTen!int).testClassTemplate.test at basics.hpp(123)
basics.d(157): Error: template instance cpp.test.testClassTemplate.testClassTemplate!(arrayOfTen!int) error instantiating
```

I guess there is a problem with Type::merge() and decorations in mtype.c...maybe? Anyways, I just took a quick look and thought that was where the problem lay.

Thanks,
Kelly

**Comment by Syniurge** [comment]
Hi Kelly,

I didn't know this could compile in C++. Even with `enum class` it still compiles, even if the int field is made public:

``` cpp
    class testClassTemplate
    {
    public:
      enum class test {
        FREE,
        DELETE
      };

      int test;
    };
```

The enum constants do not seem to be usable anymore, the int member always shadows the enum.

With a normal enum they are usable, but since D enums are scoped like `enum class` we're stuck.. Could you show me the VTK code that does this (enums having the same name as fields)?

One possible workaround would be to map such enums to anonymous D enums..

**Comment by wilsonk** [comment]
The template code is here:

http://www.vtk.org/doc/nightly/html/vtkDataArrayTemplate_8h_source.html

and DeleteMethod is the var to look for.

**Comment by Syniurge** [comment]
Okay this happens to records as well, and actually correcting myself this isn't uncommon in C/C++ to have tag types or typedefs having the same identifier as variables or functions. However the way Calypso maps tag types only nested enums/records may cause symbol conflicts (and typedefs too as they already did before with libc).

A downside of mapping to an anonymous enum is that function parameters whose type is this enum would have to be mapped to the integer type instead which may cause issues with function overloads and template specializations (although that should be extremely rare), and anyway this can't be done with records:

``` cpp
class testClass {
    struct test {};
    test test;
};
```

So I opted to prefix them instead with `§`.

**Comment by Syniurge** [comment]
By the way Kelly if there is more than one error while importing VTK or another not yet tested library and you want me to sort out the bulk of Calypso bugs, provide me some sample code and the version of the library so I can start investigating right away.
