### ISSUE TITLE
ubuntu Build instructions

### ISSUE THREAD

**Issue by mardukbp** [Syniurge/Calypso#49]
I could not find the build instructions anywhere. I figured it out how to do it by googling and making cmake happy. Here are the instructions that work for Ubuntu 16.04 in case someone else wants to try this awesome compiler:

1. Add the llvm-3.9 [repo](http://apt.llvm.org/)
2. `sudo apt-get install llvm-3.9 clang-3.9 ninja-build systemtap-sdt-dev`
3. Clone this repo and `cd` into it
4. `git submodule update --init`
5. `mkdir build && cd build`
6. `cmake ..`
7. `make`

**Comment by timotheecour** [comment]
also:
`sudo apt-get install zlib1g-dev ldc g++`

**Comment by thewilsonator** [comment]
As of a week ago this Calypso has upgraded to LLVM 5.0, so the dependancies need to be upgraded accordingly.

**Comment by timotheecour** [comment]
Oh, wow, ldc 1.7 was merged, cool! (guess it's a fast moving target, already a 1.8 beta)

**Comment by Syniurge** [comment]
I updated the build instructions, they should be clearer now?

Calypso doesn't depend on ninja-build and systemtap-sdt-dev anymore (ninja is only required for MSVC builds), and clang hasn't been needed for 1 year and a half now.
