### ISSUE TITLE
Build problem with Ubuntu 16.04

### ISSUE THREAD

**Issue by wilsonk** [Syniurge/Calypso#52]
Hey Elie,

Glad to see you are back at it here. I tried to build and ran into this issue with llvm-3.9.1/clang-3.9.1 (downloaded as source and built by hand), ldc 0.17.1:

```
[  1%] Linking CXX static library lib/libldc.a
[ 11%] Built target LDCShared
[ 11%] Generating bin/ldc2
/usr/bin/ld: /home/wilsonk/Downloads/Calypso/build/lib/libldc.a(GarbageCollect2Stack.cpp.o): undefined reference to symbol '_ZN4llvm9CallGraph19getOrInsertFunctionEPKNS_8FunctionE'
//usr/local/lib/libLLVMipa.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/ldc2.dir/build.make:61: recipe for target 'bin/ldc2' failed
make[2]: *** [bin/ldc2] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/ldc2.dir/all' failed
make[1]: *** [CMakeFiles/ldc2.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

Not sure what is going on there. Any ideas?

**Comment by wilsonk** [comment]
Hmmm, it looks like this is something specific to my setup on one machine here. I started over with a fresh VM of Ubuntu 16.04 and everything built and works fine.  (the build instructions in #49 helped to simplify things also since I had forgotten the procedure over the past year... these instructions should probably be highlighted or mentioned on the Calypso opening page, just to make it easier for others).

I still wouldn't mind any advice if you know anything about the error above, as I would like to work outside the VM :)

Thanks,
Kelly

**Comment by Syniurge** [comment]
Hey Kelly,

LLVMipa disappeared starting from LLVM 3.8 so your build was probably mixing different versions of LLVM. 

> (the build instructions in #49 helped to simplify things also since I had forgotten the procedure over the past year... these instructions should probably be highlighted or mentioned on the Calypso opening page, just to make it easier for others)

Except for Ninja the build instructions are the same for LDC and Calypso, but yes the README could be clearer about this.
(That reminds me that I forgot to add a proper FindNinja.cmake and that may cause a lot of confusion.)

**Comment by wilsonk** [comment]
This seems to be a problem specific to my system. Closing.
