### ISSUE TITLE
duplicate symbol __D6ℂcpp3std9type_info9type_info6__initZ

### ISSUE THREAD

**Issue by timotheecour** [Syniurge/Calypso#61]
on OSX, I'm getting:

duplicate symbol __D6ℂcpp3std9type_info9type_info6__initZ in:
    .calypso_cache/__cpp-std-type_info.o
    libcalypso-ldc-debug.a(__cpp_monolith-debug.o)
duplicate symbol __D6ℂcpp3std9type_info9type_info7__ClassZ in:
    .calypso_cache/__cpp-std-type_info.o
    libcalypso-ldc-debug.a(__cpp_monolith-debug.o)
duplicate symbol __D6ℂcpp3std_Cpp9type_info12__ModuleInfoZ in:
    .calypso_cache/__cpp-std-type_info.o
    libcalypso-ldc-debug.a(__cpp_monolith-debug.o)
ld: 3 duplicate symbols for architecture x86_64

when adding:
```
modmap (C++) "<vector>";
import (C++) std.vector;
```

**Comment by timotheecour** [comment]
workaround: make sure that you compile using shared libraries (not static) (for phobos,druntime,calypso) and also use https://github.com/Syniurge/Calypso/issues/60#issuecomment-358059644

**Comment by timotheecour** [comment]
https://github.com/Syniurge/Calypso/commit/244980bbd63cdc20345de7412fafb5c309a0fffb#commitcomment-27375250

@Syniurge 
> You mean statically linking against their own libraries or use incremental linking?
Just to make sure we're talking about the same thing, by incremental linking I mean packing a bunch of object files into another object file (with ld -r).
Calypso afaiu has nothing to do with ld -r producing duplicate symbols in OS X. I don't know why linkonceODR isn't being honored, but everything I've tried didn't work so I kinda gave up for now, I'd need to delve deeper into how linking is being done. Or find a better workaround e.g with something like -singleobj.

**Comment by Syniurge** [comment]
Late closing, they've been gone for a while now.
