### ISSUE TITLE
is `modmap (C++) "basics.cpp";` an error (instead of basics.h) ?

### ISSUE THREAD

**Issue by timotheecour** [Syniurge/Calypso#62]
all the code in calypso shows `modmap (C++) {foo.h or foo}`  except for:
```
tests/calypso/basics.d:14:1:modmap (C++) "basics.cpp";
```
is it an error to put the source file instead of header file? The docs don't specify which should be used; I'm guessing it's ok to add .h and .cpp; however, instructions in basics3.d shows:
```
* Build with:
 *   $ clang++ -std=c++11 -c basics.cpp -o basics.cpp.o
 *   $ ldc2 -cpp-args -std=c++11 basics.cpp.o -L-lstdc++ basics.d
 ```
will that introduce ODR violations since ldc2 command will get the obj both from basics.cpp.o and from .calypso_cache/*.o ?

**Comment by Syniurge** [comment]
>is it an error to put the source file instead of header file? 

This was for convenience when basics.d was turned into a lit test.
