### ISSUE TITLE
OSX: building calypso gives: error: unknown type name '_Unwind_Ptr' 

### ISSUE THREAD

**Issue by timotheecour** [Syniurge/Calypso#76]
IIRC i didn't use to have this problem yesterday; It may be related to having run
`xcode-select --install`

In file included from /Users/timothee/git_clone/D/Calypso/build5/runtime/calypso-ldc-debug-cpp/calypso_cache.h:1:
/Users/timothee/git_clone/D/Calypso/runtime/calypso/cpp/eh/unwind-cxx.h:92:3: error: unknown type name '_Unwind_Ptr'
  _Unwind_Ptr catchTemp;

**Comment by Syniurge** [comment]
Until macOS support improves, in unwind.h it's defined as: 

```cpp
typedef uintptr_t _Unwind_Ptr;
```

**Comment by timotheecour** [comment]
I saw that but there'll be a bunch of other errors besides that, that was just the 1st one.

the following WORKAROUND did the trick:

in Calypso/runtime/calypso/cpp/eh/unwind-cxx.h:
replace

`#include "unwind.h"` 

with something like:

#include "/Users/timothee/temp/brew/Cellar/gcc/7.2.0/lib/gcc/7/gcc/x86_64-apple-darwin17.2.0/7.2.0/include/unwind.h"

a better workaround is needed but that should help others with this issue.

**Comment by timotheecour** [comment]
here's a better fix:

update this as needed on your system

gcc_D=/Users/timothee/homebrew//Cellar/gcc/7.2.0/

ccmake -D LLVM_CONFIG=$homebrew_D/Cellar/llvm@3.9/3.9.1_1/bin/llvm-config -D D_FLAGS="-cpp-args=-I$gcc_D/include/c++/7.2.0;-cpp-args=-I$gcc_D/include/c++/7.2.0/x86_64-apple-darwin17.2.0;-cpp-args=-I$gcc_D/lib/gcc/7/gcc/x86_64-apple-darwin17.2.0/7.2.0/include" ..

that's the minimal set of flags that work for me on OSX

NOTE: this can be closed once build instructions for OSX are updated on readme.md

**Comment by timotheecour** [comment]
updated README in https://github.com/Syniurge/Calypso/commit/9cb71871b6e15eea875d2e309e70b409bb2d3dc9 so closing this
