### ISSUE TITLE
`pragma(modmap, C++, "util.h")` vs `modmap(C++) "util.h"`

### ISSUE THREAD

**Issue by timotheecour** [Syniurge/Calypso#83]
* it allows for compilers that are not aware of modmap syntax to compile the file, eg:

```
version(Calypso){
pragma(modmap, C++, "util.h");
pragma(import, C++){
  import _;
  import std._ : bar;
}
} else { // not Calypso
  void bar(){
   // workaround, less efficient implementation
  }
}
```

NOTE: with current syntax, this would require a mixin(`modmap(C++) "util.h"`); which is less readable.

* it allows reusing all the existing features of pragmas, eg applying to all, one, or a scope of declarations: `pragma(x) foo;, pragma(x): foo; //till end, pragma(x){foo;...}`

```
pragma(modmap, C++, "util.h") {
pragma(import, C++)
import _ : bar;
}
pragma(modmap, C++, "other_header_with_name_clashes.h") {
pragma(import, C++)
import _ : bar2 = bar;
}
```
is there a simple way to do this with current syntax?

* would work out of the box with existing tools that need to parse D code without requiring any changes on their side:
dscanner, IDE's  that use syntax highlighting etc

* how about defining a builtin `version(Calypso)`? (as noted above)
* typically there would be only a small number of modmap calls, so typing `modmap(C++) "util.h" ` vs `pragma(modmap, C++, "util.h")` is not a big difference

**Comment by Syniurge** [comment]
I concur, introducing that keyword wasn't a good move and it's not particularly elegant. OTOH I like the `import (C++)` aesthetics and if Calypso gets traction we could talk with the DMD and Dscanner guys to add this to their parsers, it's not a big addition.

`pragma(modmap)` is the way to go. However 

> it allows reusing all the existing features of pragmas, eg applying to all, one, or a scope of declarations

is something to explore but it may not be easy to implement.

> how about defining a builtin version(Calypso)? (as noted above)

Will do.

**Comment by timotheecour** [comment]
> is something to explore but it may not be easy to implement.

but at least pragma based syntax opens up possibility for a future implementation of that. Anyway looks like we're in agreement :)

**Comment by timotheecour** [comment]
closing in favor of https://github.com/Syniurge/Calypso/blob/documentation/calypso_proposal_pragma.md
