### ISSUE TITLE
`A a=get_A;` doesn't call dtor upon exiting scope; `auto a=get_A;` works

### ISSUE THREAD

**Issue by timotheecour** [Syniurge/Calypso#84]
* both `auto a=` and `A a=` should be doing the same thing.

`A a=get_A;` is the buggy one

```
// util.cpp:
A get_A(){
  return A(20);
}

// main.d:
void main(){
  A a=get_A; // doesn't call dtor upon exiting scope
  auto a=get_A; // ok
}
```

NOTE:
* 1st priority should be making sure code is not buggy (eg matching ctor/dtor counts; making sure internal pointers bug regressions are not re-introduced after https://github.com/Syniurge/Calypso/issues/70 was fixed)
* after that, looking into optimizations, eg making sure that un-necessary copy constructors are elided, and making use of C++ move ctors when possible.
* a possible optimization would be to allow annotating which C++ classes are implicitly-movable (in the sense of D move semantics via a simple memcpy), see https://github.com/Syniurge/Calypso/issues/78 for discussion on syntax

* this is related (but maybe not identical) to https://github.com/Syniurge/Calypso/issues/72

**Comment by Syniurge** [comment]
Does your `cv.Mat` code behave properly now with the latest commits?

**Comment by timotheecour** [comment]
yes! and code in bug report now works! thanks! closing
